{% set name = "pytest-sugar" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6422e83258f5b0c04ce7c632176c7732cab5fdb909cb39cca5c9139f81276c0a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - packaging >=21.3
    - pytest >=6.2.0
    - termcolor >=2.1.0

test:
  imports:
    - pytest_sugar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pivotfinland.com/pytest-sugar/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a plugin for py.test that changes the default look and feel of py.test '
  description: |
    pytest-sugar is a plugin for py.test that shows failures and errors instantly and
    shows a progress bar.
  dev_url: https://github.com/Teemu/pytest-sugar/

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - ocefpaf
