{% set name = "pytest-sugar" %}
{% set version = "0.9.1" %}
{% set sha256 = "ab8cc42faf121344a4e9b13f39a51257f26f410e416c52ea11078cdd00d98a2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - termcolor
    - py
    - pytest

test:
  imports:
    - pytest_sugar

about:
  home: https://github.com/Frozenball/pytest-sugar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a plugin for py.test that changes the default look and feel of py.test '
  description: |
      pytest-sugar is a plugin for py.test that shows failures and errors instantly and 
      shows a progress bar.  
  doc_url: http://pydoc.net/pytest-sugar/0.8.0/
  dev_url: https://github.com/Frozenball/pytest-sugar

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
